# Julia Reference Guide
Ana Paula Ruhe
---

## Basics

* Comment symbol: #  
* Help: `?object` 
* `@show` macro: print the code as well as the output. 

In [1]:
@show x = 1 + 2

x = 1 + 2 = 3


3

* We can use `;` at the end of the line to supress the output.

In [2]:
@show x = 1 + 2;

x = 1 + 2 = 3


* Create an object of the same size/type than other: `similar` function

In [ ]:
y = similar(x)

* `LaTeXStrings` package: allows using LaTeX symbols in plots (as in legends os axis).  
In the text, use `L"math expression"`. Ex: `L"x^2"` will display $x^2$.

* Printing text and variables values: `println()` function.  
  + To show the value of a variable $x$, we use: 

In [ ]:
println("The result is x = $x.")

#### `for` loop syntax:

In [ ]:
for i in 1:n
  ...
end

When filling a vector, it is best to use the `eachindex` term:

In [ ]:
# Example: generating a vector ϵ of 100 random numbers
n = 100
ϵ = zeros(n)
for i in eachindex(ϵ)
    ϵ[i] = randn()
end

Here, `eachindex(ϵ)` returns an iterator of indices which can be used to access ϵ. Iterators are memory efficient because the elements are generated on the fly rather than stored in memory, and it allows the compiler flexibility to creatively generate fast code.

In Julia you can also loop directly over arrays themselves:

In [ ]:
ϵ_sum = 0.0 # A floting point; ϵ = 0 would create a integer. 
m = 5
for ϵ_val in ϵ[1:m]
    ϵ_sum = ϵ_sum + ϵ_val
end

#### Function syntax:

In [ ]:
function name(parameters)
    ...
    return y
end

* When no return statement is present, the last value obtained when executing the code block is returned. Although some prefer the second option, we often favor the former on the basis that explicit is better than implicit.
* Function arguments can be given default values.
  + If the argument is not supplied, the default value is substituted.

In [ ]:
f(x, a = 1) = exp(cos(a * x))

* Keywords arguments: a way of separating the arguments with default values, so they can be called by name.

In [ ]:
a = 2
f(x;a) = exp(cos(a*x))    # Will use the value for variable called a

* Broadcasting: applying a function in an iterated way.
  + If `f` is any Julia function, then `f.` references the broadcasted version.

#### Logical connectors
* `&&` (and) `||` (or).
  + `P && Q` is true if both are true, otherwise it’s false.
  + `P || Q` is false if both are false, otherwise it’s true.

## Packages and Version Control 

In order to create a new project, create a directory for it and then activate that directory to make it the "active project" which package operations manipulate.

* Consult current directory: `pwd()`
* Change directory: `cd("endereço\do\projeto")`

* Creating a project:
  + Open VSCode in the **parent** folder.
  + Open Julia REPL.
  + Check the current directory. 
  + Create the project: `] generate nomedoprojeto`. This will create Project.toml and Manifest.toml files, which provide an isolated set of packages for a particular project.
  + Set the folder as directory: `cd("Nome_do_Projeto")` (hit back to leave package mode)
  + Activate the project: `] activate .`
  + Check the status of the project (it will be empty before any packages are loaded): `] st`
  + Obs: to "deactivate" the environment, use `] activate ` with no complements. It will return to Julia's standard env.
* Select the new environment in VSCode: lower-right corner, in `Julia env:`


If you load a jupyter notebook, it will automatically look up the tree for the project files to activate, but will not automatically install them. 

* To install the packages, use the `] instantiate` command (if you are loading a directory that already has packages).
* To install packages in a new project, use:  
  + `using Pkg` 
  + `Pkg.add("NameOfPackage")`

The project files can be in parent folders relative to the notebooks and sourcecode.

Using a project provides the environment for running code is reproducible, so that anyone can replicate the precise set of package and versions used in construction.

After the installation and activation, `using` provides a way to say that a particular code or notebook will use the package.


### Python and Conda
It might be necessary to change the following settings:  
* `ENV["CONDA_JL_HOME"] = "C:/Users/anapn/miniforge3"` 
* `using Pkg`
* `Pkg.build("Conda")`


## Data Structures

### Data types

* **Assessing the type of a variable:** function `typeof()`  

* Boolean: `TRUE` and `FALSE` 
* Integers: `x = 1`  
* Floats: `x = 1.0`
* Strings: "Text"  
  + Using `$` inside of a string shows the value of a variable: "The result is x = $x".  
  + We can concatenate (colar) strings using `*`:


In [3]:
x = "ice"
y = "cream"
x*y

"icecream"

* Functions for working with strings:   

In [12]:
s = "very long text"

# Split function:
@show split(s)

  # Default is to separate at blank space. You can pass the separator as a string second element. Ex: split(s,","). 

split(s) = SubString{String}["very", "long", "text"]


3-element Vector{SubString{String}}:
 "very"
 "long"
 "text"

In [11]:
# Replace function:
@show replace(s, "long" => "short");

replace(s, "long" => "short") = "very short text"


In [14]:
# Strip function: Remove white space
@show strip("   Hello   ");


strip("   Hello   ") = "Hello"


### Arrays

* Ordered (like Tuples, unlike Dictionaries) and mutable (unlike Tuples, like Dictionaries)
  + Syntax:

In [21]:
HIMYM = ["Ted", "Robin", "Lily", "Marshall", "Barney"]

5-element Vector{String}:
 "Ted"
 "Robin"
 "Lily"
 "Marshall"
 "Barney"

* Array elements are referenced using square brackets `[]` (unlike MATLAB and Fortran).
* Array indices start at 1.  
* An array is identified as:  `Array{type,n}`
  + For example, `HIMYM` is Array{String,1}: a one dimensional vector.
  + A numerical matrix would be Array{Float,2} 

In [27]:
mymatrix = [1 2 3; 4 5 6]

2×3 Matrix{Int64}:
 1  2  3
 4  5  6

In [28]:
rand(3,3,2)

3×3×2 Array{Float64, 3}:
[:, :, 1] =
 0.660234  0.382535  0.489083
 0.716385  0.547163  0.551098
 0.227274  0.409996  0.561599

[:, :, 2] =
 0.520419  0.851311  0.409233
 0.22281   0.94307   0.54712
 0.557216  0.386375  0.618318

* Array of arrays:

In [35]:
things = [["chocolate", "strawberries"],["pencils","notebooks"]]

2-element Vector{Vector{String}}:
 ["chocolate", "strawberries"]
 ["pencils", "notebooks"]

#### Indexing

* Take elements of an array, or update elements: 

In [29]:
HIMYM[3]

"Lily"

In [31]:
HIMYM[5] = "Ranjit"

"Ranjit"

* To add a new element: `push!`

In [32]:
push!(HIMYM, "Barney")

6-element Vector{String}:
 "Ted"
 "Robin"
 "Lily"
 "Marshall"
 "Ranjit"
 "Barney"

* To remove the last element: `pop!`

* The last element of an array can be referenced with `end`. 
* We can also use `end` recursively or with slide notation:

In [38]:
HIMYM[end]

"Ranjit"

In [41]:
HIMYM[end-1]

"Marshall"

In [39]:
HIMYM[3:end]

3-element Vector{String}:
 "Lily"
 "Marshall"
 "Ranjit"

* Booleans can be used to extract elements:

In [22]:
@show a = randn(2, 2)
@show b = [true false; false true]
@show a[b]         # Get elements [1,1] and [2,2] of a        

a = randn(2, 2) = [-1.0542446692398801 0.6350933151585837; -0.06470036467277628 2.081498510690278]
b = [true false; false true] = Bool[1 0; 0 1]
a[b] = [-1.0542446692398801, 2.081498510690278]


2-element Vector{Float64}:
 -1.0542446692398801
  2.081498510690278

* Change dimension of array: `reshape(x,n,m)`

#### Copy an Array

* Using the `=` sign **does not** create an independent copy of an array. Rather, it creates a new way to access the old array.
* Modifications done to the "copy" will affect the old array as well.
* To create an independent copy, use the `copy` function  

`newarray = copy(oldarray)`

* The `=` binds the name of the object to the value of the other object. 
* The `.=` assigns values. 

In [33]:
x = [1 2 3]
y = x         # Now name `y` is binded to whatever `x` is
z = [2 3 4]
y .= z        # Now the values in z are attributed to name `y` (hence, the values in x change)
@show (x, y, z);

(x, y, z) = ([2 3 4], [2 3 4], [2 3 4])


In [34]:
x = [1 2 3]
y .= x
x = [0 0 0]
@show (x, y);

(x, y) = ([0 0 0], [1 2 3])


Another way to assign values: `y[:] = z`

In [35]:
y[:] = z

1×3 Matrix{Int64}:
 2  3  4

* The `===` operator tests if two objects share the same memory (two names binded to the same value)

In [36]:
y === z

false

#### Create an Array

* Function `zeros()`: can create single ou multivariate arrays of zeros.  
  + `zeros(n)`
  + `zeros(n,m)`  
* Function `fill(x,n,m)`: creates an $n \times m$ array with all entries equal to $x$.  
* Function `Array{Float64}(undef,n,m)`: creates an empty array of Float type with size $n \times m$.
* Important: vector $\times$ row matrix:   

In [44]:
x = [1,2,3,4]
@show typeof(x)

y = [1 2 3 4] 
@show typeof(y)

dropdims(y, dims = 1)    # Turn into a 1-dimensional array

typeof(x) = Vector{Int64}
typeof(y) = Matrix{Int64}


4-element Vector{Int64}:
 1
 2
 3
 4

* Equivalent of **linspace**: `range()`

In [51]:
maxval = 1.0
minval = 0.0
n = 10
a = range(minval, maxval, length=n)
b[:] = Vector(a) 

10-element Vector{Float64}:
 0.0
 0.1111111111111111
 0.2222222222222222
 0.3333333333333333
 0.4444444444444444
 0.5555555555555556
 0.6666666666666666
 0.7777777777777778
 0.8888888888888888
 1.0

#### Matrices

* Transpose:

In [ ]:
a = [1 2; 3 4]
b = a'            # Transpose
@show typeof(b)   # It isn't a matrix, even though a is one
c = Matrix(b)     # Convert to matrix

* Diagonal:
  + The `diagonal()` function creates an object which is not a dense matrix - more efficient.

In [29]:
using LinearAlgebra
a = [1.0, 2.0]
d = LinearAlgebra.Diagonal(a)

2×2 Diagonal{Float64, Vector{Float64}}:
 1.0   ⋅ 
  ⋅   2.0

* Identity matrix: `I` object (no need to atribute its dimension)

In [31]:
b = [1.0 2.0; 3.0 4.0]
b - I

2×2 Matrix{Float64}:
 0.0  2.0
 3.0  3.0

* Element-wise multiplication: `.*`
* Matrix multiplication: `*` when working with 2-dimensional arrays  
  + For 1-dimensional arrays, one should be transposed (as below) or use `dot()` function
  

In [40]:
@show x = ones(2)
@show typeof(x)
x' * x

x = ones(2) = [1.0, 1.0]
typeof(x) = Vector{Float64}


2.0

In [41]:
x ⋅ x

2.0

* Solving linear system: to solve $Ax = b$, use `x = A \ b`
* Scalar addition (unlike MATLAB) should use element-wise operator: `A .+ 1`
* Element-wise comparisons: `a .> b` or `a .== b` 

#### Linear Algebra

`using LinearAlgebra`
* Determinant: `det(A)`  
* Trace: `tr(A)` 
* Eigenvalues: `eigvals(A)`
* Rank: `rank(A)`

### Tuples


* An ordered collection of elements, enclosed by parenthesis.
* Tuples elements are immutable: we **can't** update it.
  + Sintax: 

In [ ]:
animals = ("penguins", "dogs", "dolphins")

("penguins", "dogs", "dolphins")

* Named tuples:

In [ ]:
animals = (bird = "penguis", pet = "dogs", aquatic = "dolphins")

(bird = "penguis", pet = "dogs", aquatic = "dolphins")

* Tuples can be indexed:

In [ ]:
animals[1]

"penguis"

In [ ]:
animals.pet

"dogs"

* Tuples are good for assigning parameters values

In [52]:
function f(p)
    (;α, β) = p                   # Unpacking notion: says to take elements α and β from the object parameters
    return α + β
end

parameters = (;α = 0.1, β = 0.2)  # Assigning values
f(parameters)                     # Applying the function to the values 

0.30000000000000004

### Dictionaries


* A set of data related to another.
* It is not ordered, so can't be indexed.
* Classic example: a contact list, which relates a name to a phone number. 
  + Syntax:

In [ ]:
Dict(key1 => value1, key2 => value2, ...)

In [ ]:
# Ex: contact list
contacts = Dict("Ana" => "3333-1111", "Rafa" => "9999-8888")

Dict{String, String} with 2 entries:
  "Rafa" => "9999-8888"
  "Ana"  => "3333-1111"

In [ ]:
# Getting an element:
contacts["Rafa"] 

"9999-8888"

In [ ]:
# Adding an element:
contacts["Duda"] = "9898-3131"
contacts   # See the elements 

Dict{String, String} with 3 entries:
  "Rafa" => "9999-8888"
  "Ana"  => "3333-1111"
  "Duda" => "9898-3131"

* Removing an element: `pop!` function

In [ ]:
pop!(contacts, "Duda")

"9898-3131"